### ISSUE TITLE
Event Details for each event are to be kept separately in a new Page

### ISSUE THREAD

**Issue by himanshu-balasamanta** [Prastuti-IIT-BHU/templates#6]
A separate Event Page with each event having
- [x] Event Name
- [x] basic info
- [ ] registration link

@ManasAsati , anything else?

**Comment by ManasAsati** [comment]
Explore more link redirects to a page containing **Event Name, Details, Workshops and PS.**

Registration link will be present only in main page event block and not in Explore More page.

**Comment by ManasAsati** [comment]
![Frontend](https://user-images.githubusercontent.com/44468527/106358028-b539aa00-632f-11eb-9303-e55e30834998.PNG)
